spring.application.name=LibraryManagement




spring.datasource.url=jdbc:postgresql://localhost:5432/librarymanagement
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.batch_size=100
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.generate_statistics=true

spring.flyway.enabled=true
spring.flyway.baseline-description="init"
spring.flyway.baseline-version=0
spring.flyway.user=postgres
spring.flyway.password=1234

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
